### ISSUE TITLE
Port not found/unable to connect when trying to send code to device

### ISSUE THREAD

**Issue by traumverloren** [thingsSDK/thingssdk-cli#45]
I am getting the following error message and unable to connect to my device. Any way I can **try** to help, I'm happy to!

Device: Adafruit Feather Huzzah (Successfully flashed using Flasher.js (binaries v1.91))

I also  downgraded my npm/node version from the latest, this is on version:
node v6.11.1
npm 3.10.10

```
$ npm run deploy

> js-pixels@0.0.0 deploy /Users/Stephanie/projects/js-pixels
> node ./scripts/upload production

Treeshaking code...
Sending code to device - /dev/cu.SLAB_USBtoUART @ 115200 baud...
espruino:  Espruino Command-line Tool 0.0.23
-----------------------------------

espruino:  Connecting to '/dev/cu.SLAB_USBtoUART'
espruino:  Port "/dev/cu.SLAB_USBtoUART" not found
Unable to connect!
Exited with status 0%
```

`Devices.json`:
```
{
  "devices": {
    "/dev/cu.SLAB_USBtoUART": {
      "baud_rate": 115200,
      "runtime": "espruino"
    }
  }
}
```

**Comment by chalkers** [comment]
Can you share with me you package.json / package lock or yarn lock files?

**Comment by red62labs** [comment]
same issue 
device : nodemcu amica esp8266

{
  "name": "test-firm",
  "version": "0.0.0",
  "private": true,
  "main": "main.js",
  "scripts": {
    "dev": "node ./scripts/upload development && npm run repl",
    "deploy": "node ./scripts/upload production",
    "repl": "node ./scripts/repl"
  },
  "devDependencies": {
    "thingssdk-deployer": "~1.0.1",
    "thingssdk-espruino-strategy": "~1.0.2"
  }
}

**Comment by red62labs** [comment]
I am also on a mac

**Comment by chevdor** [comment]
same issue, OSX, ESP32.
The serial port is definitely available:
```
$ ll /dev/cu.SLAB_USBtoUART 
crw-rw-rw-  1 root  wheel   21,  23 Jan 11 11:30 /dev/cu.SLAB_USBtoUART
```
The espruino IDE connects successfully. I performed the test withOUT Espruino IDE connected and running.

I am also using: 
```
"thingssdk-deployer": "~1.0.1",
"thingssdk-espruino-strategy": "~1.0.2"
```

**Comment by chevdor** [comment]
The issue is in:
https://github.com/espruino/EspruinoTools

Using master instead of 0.0.23 fixes the issue.

You can try running:
```
npm install https://github.com/espruino/EspruinoTools
```

**Comment by chalkers** [comment]
Sorry for delay. I've updated the `thingssdk-espruino-strategy` to use the latest Espruino CLI.

You also need a postinstall script for the package.json like so `"postinstall": "rimraf node_modules/bluetooth-hci-socket"`.

Please upgrade your package.json to include the `thingssdk-espruino-strategy` to `~1.0.3`.

Also, please upgrade globally `thingssdk-cli` to `1.3.0`.

Currently the ESP32 isn't 'supported' but it may work :)

Your package.json should look like this:

```
{
  "name": "sampleproject",
  "version": "0.0.0",
  "private": true,
  "main": "main.js",
  "scripts": {
    "dev": "node ./scripts/upload development && npm run repl",
    "deploy": "node ./scripts/upload production",
    "repl": "node ./scripts/repl",
    "postinstall": "rimraf node_modules/bluetooth-hci-socket"
  },
  "devDependencies": {
    "thingssdk-deployer": "~1.0.1",
    "thingssdk-espruino-strategy": "~1.0.3"
  }
}
```

**Comment by haricane8133** [comment]
hi, @chalkers , i'm currently using the latest version of thingssdk-cli (and the package.json is as you have said). Still getting the same error. i'm running windows 10. the OS detects the ESP8266 (NodeMCU V3) board that i'm having, properly in COM3. I've also run the flasher.js with the latest version of espruino. the problem is when I try to 'npm run dev' or 'npm run repl' or 'npm run deploy'. the exact error says : "

**Connecting REPL...
espruino:  Espruino Command-line Tool 0.1.6
-----------------------------------

espruino:  Connecting to 'COM3'
espruino:  Port "COM3" not found
espruino:  Unable to connect!
Exited with status 0**
"

NOTE: in order to install thingssdk-cli, I had to install python 2.7 and "npm install -g --production windows-build-tools"

also, when I give npm install in the project directory after "thingssdk new <projectname>", I could see a lot of logged messages preceded with "**gyp ERR!**"

hope you can resolve this issue...

**Comment by chevdor** [comment]
Following the instructions from @chalkers, it also still does not work for me on OSX. Despite all the updates and cleanup.

**Comment by siberian1967** [comment]
Same problem here. Espruino connects fine but thinkssdk gives me these same errors on my mac.

Using package.json as suggested above as well.
